/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dbapi;

import dbapi.data.Table;
import org.yaml.snakeyaml.Yaml;

import java.io.FileInputStream;
import java.io.InputStream;
import java.io.IOException;
import java.util.List;
import java.util.Map;

public class App {

    public static void main(String[] args) throws IOException {

        Yaml yaml = new Yaml();
        InputStream input = new FileInputStream("input.yaml");

        Map<String, Object> obj = (Map) yaml.load(input);

        String javaSrcPath = (String) obj.get("javaSrcPath");
        String javaPackage = (String) obj.get("javaPackage");
        String javaPackagePath = javaPackage.replace(".", "/");
        String javaFullPath = javaSrcPath + javaPackagePath;
        String resourcePath = (String) obj.get("resourcePath");

        SchemaParser sp = new SchemaParser();
        List<Table> tables = sp.parse(obj);

        SqlGenerator sqlGenerator = new SqlGenerator();

        RepositoryGenerator repositoryGenerator = new RepositoryGenerator();

        HibernateGenerator hibernateGenerator = new HibernateGenerator();

        sqlGenerator.writeDatabaseFile(resourcePath, tables);

        for (Table table : tables) {
            repositoryGenerator.writeRepositoryFile(javaPackage, javaFullPath, table);
            hibernateGenerator.writeHibernateFile(javaPackage, javaFullPath, table);
        }
    }
}
